add support for `SELECT .. ORDER BY ...`
supabase/postgres_lsp pull request #102
Opened 2024-01-02 10:47 UTC by mobley-trent

#51

2024-01-02 11:48 UTC, psteinroe requested changes
This is already supported. See failing test. It's part of the sort by node.

2024-01-02 14:56 UTC, mobley-trent commented
It didn't seem to be supported with the `SELECT` statement though. I ran the test initially and the token vector returned by the testing function only had the `SELECT` and `FROM` tokens, the `ORDER` and `BY` tokens were not returned.

2024-01-02 18:32 UTC, psteinroe commented
Yes, because the tokens are not supposed to be part of the SelectStmt node. If you instead pass the SortBy node to the test function it will return the tokens. Or just add a select with order by to the e2e test. It will pass.

2024-01-25 07:45 UTC, psteinroe approved these changes

2024-01-25 07:45 UTC, merged